routes/web.php
<?php

use App\Http\Controllers\Admin\ArticlesController as AdminArticlesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Articles\ArticlesController;
use App\Http\Controllers\Articles\AuthoredArticles;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\GithubController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\Forum\TagsController;
use App\Http\Controllers\Forum\ThreadsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReplyAbleController;
use App\Http\Controllers\ReplyController;
use App\Http\Controllers\Settings\ApiTokenController;
use App\Http\Controllers\Settings\PasswordController;
use App\Http\Controllers\Settings\ProfileController as ProfileSettingsController;
use App\Http\Controllers\SocialImageController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Middleware\Authenticate;
use Illuminate\Support\Facades\Route;

Route::feeds();

// Home
Route::get('/', [HomeController::class, 'show'])->name('home');
Route::view('rules', 'rules')->name('rules');
Route::view('terms', 'terms')->name('terms');
Route::view('privacy', 'privacy')->name('privacy');
Route::get('bin/{paste?}', [HomeController::class, 'pastebin']);

Route::get('articles/{article}/social.png', SocialImageController::class)->name('articles.image');

// Authentication
Route::namespace('Auth')->group(function () {
    // Sessions
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.post');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    // Registration
    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register'])->name('register.post');

    // Password reset
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.forgot');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.forgot.post');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.reset.post');

    // Email address verification
    Route::get('email/verify', [VerificationController::class, 'show'])->name('verification.notice');
    Route::get('email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify');
    Route::post('email/resend', [VerificationController::class, 'resend'])->name('verification.resend');

    // Social authentication
    Route::get('login/github', [GithubController::class, 'redirectToProvider'])->name('login.github');
    Route::get('auth/github', [GithubController::class, 'handleProviderCallback']);
});

// Users
Route::redirect('/dashboard', '/user');
Route::get('user/{username?}', [ProfileController::class, 'show'])->name('profile');

// Notifications
Route::view('notifications', 'users.notifications')->name('notifications')->middleware(Authenticate::class);

// Settings
Route::get('settings', [ProfileSettingsController::class, 'edit'])->name('settings.profile');
Route::put('settings', [ProfileSettingsController::class, 'update'])->name('settings.profile.update');
Route::delete('settings', [ProfileSettingsController::class, 'destroy'])->name('settings.profile.delete');
Route::put('settings/password', [PasswordController::class, 'update'])->name('settings.password.update');
Route::post('settings/api-tokens', [ApiTokenController::class, 'store'])->name('settings.api-tokens.store');
Route::delete('settings/api-tokens', [ApiTokenController::class, 'destroy'])->name('settings.api-tokens.delete');

// Forum
Route::prefix('forum')->group(function () {
    Route::get('/', [ThreadsController::class, 'overview'])->name('forum');
    Route::get('create-thread', [ThreadsController::class, 'create'])->name('threads.create');
    Route::post('create-thread', [ThreadsController::class, 'store'])->name('threads.store');

    Route::get('{thread}', [ThreadsController::class, 'show'])->name('thread');
    Route::get('{thread}/edit', [ThreadsController::class, 'edit'])->name('threads.edit');
    Route::put('{thread}', [ThreadsController::class, 'update'])->name('threads.update');
    Route::delete('{thread}', [ThreadsController::class, 'delete'])->name('threads.delete');
    Route::post('{thread}/lock', [ThreadsController::class, 'lock'])->name('threads.lock');
    Route::put('{thread}/mark-solution/{reply}', [ThreadsController::class, 'markSolution'])->name('threads.solution.mark');
    Route::put('{thread}/unmark-solution', [ThreadsController::class, 'unmarkSolution'])->name('threads.solution.unmark');
    Route::post('{thread}/subscribe', [ThreadsController::class, 'subscribe'])->name('threads.subscribe');
    Route::post('{thread}/unsubscribe', [ThreadsController::class, 'unsubscribe'])->name('threads.unsubscribe');

    Route::get('tags/{tag}', [TagsController::class, 'show'])->name('forum.tag');
});

// Replies
Route::post('replies', [ReplyController::class, 'store'])->name('replies.store');
Route::get('replies/{reply}/edit', [ReplyController::class, 'edit'])->name('replies.edit');
Route::put('replies/{reply}', [ReplyController::class, 'update'])->name('replies.update');
Route::delete('replies/{reply}', [ReplyController::class, 'delete'])->name('replies.delete');
Route::get('replyable/{id}/{type}', [ReplyAbleController::class, 'redirect'])->name('replyable');

// Subscriptions
Route::get('subscriptions/{subscription}/unsubscribe', [SubscriptionController::class, 'unsubscribe'])
    ->name('subscriptions.unsubscribe');

// Articles
Route::prefix('articles')->group(function () {
    Route::get('authored', AuthoredArticles::class)->name('user.articles');
    Route::get('/', [ArticlesController::class, 'index'])->name('articles');
    Route::get('create', [ArticlesController::class, 'create'])->name('articles.create');
    Route::post('/', [ArticlesController::class, 'store'])->name('articles.store');
    Route::get('{article}', [ArticlesController::class, 'show'])->name('articles.show');
    Route::get('{article}/edit', [ArticlesController::class, 'edit'])->name('articles.edit');
    Route::put('{article}', [ArticlesController::class, 'update'])->name('articles.update');
    Route::delete('{article}', [ArticlesController::class, 'delete'])->name('articles.delete');
});

// Admin
Route::prefix('admin')->name('admin')->group(function () {
    Route::get('/', [AdminArticlesController::class, 'index']);

    // Users
    Route::get('users', [UsersController::class, 'index'])->name('.users');
    Route::put('users/{username}/ban', [UsersController::class, 'ban'])->name('.users.ban');
    Route::put('users/{username}/unban', [UsersController::class, 'unban'])->name('.users.unban');
    Route::delete('users/{username}', [UsersController::class, 'delete'])->name('.users.delete');

    // Articles
    Route::put('articles/{article}/approve', [AdminArticlesController::class, 'approve'])->name('.articles.approve');
    Route::put('articles/{article}/disapprove', [AdminArticlesController::class, 'disapprove'])->name('.articles.disapprove');
    Route::put('articles/{article}/decline', [AdminArticlesController::class, 'decline'])->name('.articles.decline');
    Route::put('articles/{article}/pinned', [AdminArticlesController::class, 'togglePinnedStatus'])->name('.articles.pinned');
});

app/Models/User.php
<?php

namespace App\Models;

use App\Concerns\HasTimestamps;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Laravel\Sanctum\HasApiTokens;

final class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens;
    use HasFactory;
    use HasTimestamps;
    use Notifiable;

    const TABLE = 'users';

    const DEFAULT = 1;
    const MODERATOR = 2;
    const ADMIN = 3;

    /**
     * {@inheritdoc}
     */
    protected $table = 'users';

    /**
     * {@inheritdoc}
     */
    protected $fillable = [
        'name',
        'email',
        'twitter',
        'username',
        'password',
        'ip',
        'github_id',
        'github_username',
        'type',
        'remember_token',
        'bio',
    ];

    /**
     * {@inheritdoc}
     */
    protected $hidden = ['password', 'remember_token'];

    public function id(): int
    {
        return $this->id;
    }

    public function name(): string
    {
        return $this->name;
    }

    public function emailAddress(): string
    {
        return $this->email;
    }

    public function username(): string
    {
        return $this->username;
    }

    public function bio(): string
    {
        return $this->bio;
    }

    public function githubUsername(): string
    {
        return $this->github_username ?? '';
    }

    public function twitter(): ?string
    {
        return $this->twitter;
    }

    public function hasTwitterAccount(): bool
    {
        return ! empty($this->twitter());
    }

    public function isBanned(): bool
    {
        return ! is_null($this->banned_at);
    }

    public function type(): int
    {
        return (int) $this->type;
    }

    public function isModerator(): bool
    {
        return $this->type() === self::MODERATOR;
    }

    public function isAdmin(): bool
    {
        return $this->type() === self::ADMIN;
    }

    public function isLoggedInUser(): bool
    {
        return $this->id() === Auth::id();
    }

    public function hasPassword(): bool
    {
        $password = $this->getAuthPassword();

        return $password !== '' && $password !== null;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function threads()
    {
        return $this->threadsRelation;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function latestThreads(int $amount = 5)
    {
        return $this->threadsRelation()->latest()->limit($amount)->get();
    }

    public function deleteThreads()
    {
        // We need to explicitly iterate over the threads and delete them
        // separately because all related models need to be deleted.
        foreach ($this->threads() as $thread) {
            $thread->delete();
        }
    }

    public function threadsRelation(): HasMany
    {
        return $this->hasMany(Thread::class, 'author_id');
    }

    public function countThreads(): int
    {
        return $this->threadsRelation()->count();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function replies()
    {
        return $this->replyAble;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function latestReplies(int $amount = 10)
    {
        return $this->replyAble()->latest()->limit($amount)->get();
    }

    public function deleteReplies()
    {
        // We need to explicitly iterate over the replies and delete them
        // separately because all related models need to be deleted.
        foreach ($this->replyAble()->get() as $reply) {
            $reply->delete();
        }
    }

    public function countReplies(): int
    {
        return $this->replyAble()->count();
    }

    public function replyAble(): HasMany
    {
        return $this->hasMany(Reply::class, 'author_id');
    }

    public function articles(): HasMany
    {
        return $this->hasMany(Article::class, 'author_id');
    }

    public function latestArticles(int $amount = 10)
    {
        return $this->articles()->approved()->latest()->limit($amount)->get();
    }

    public function countArticles(): int
    {
        return $this->articles()->approved()->count();
    }

    public static function findByUsername(string $username): self
    {
        return static::where('username', $username)->firstOrFail();
    }

    public static function findByEmailAddress(string $emailAddress): self
    {
        return static::where('email', $emailAddress)->firstOrFail();
    }

    public static function findByGithubId(string $githubId): self
    {
        return static::where('github_id', $githubId)->firstOrFail();
    }

    public function delete()
    {
        $this->deleteThreads();
        $this->deleteReplies();

        parent::delete();
    }

    public function countSolutions(): int
    {
        return $this->replyAble()->isSolution()->count();
    }

    public function scopeMostSolutions(Builder $query, int $inLastDays = null)
    {
        return $query->withCount(['replyAble as solutions_count' => function ($query) use ($inLastDays) {
            $query->where('replyable_type', 'threads')
                ->join('threads', 'threads.solution_reply_id', '=', 'replies.id');

            if ($inLastDays) {
                $query->where('replies.created_at', '>', now()->subDays($inLastDays));
            }

            return $query;
        }])->orderBy('solutions_count', 'desc');
    }

    public function scopeMostSubmissions(Builder $query, int $inLastDays = null)
    {
        return $query->withCount(['articles as articles_count' => function ($query) use ($inLastDays) {
            if ($inLastDays) {
                $query->where('articles.approved_at', '>', now()->subDays($inLastDays));
            }

            return $query;
        }])->orderBy('articles_count', 'desc');
    }

    public function scopeMostSolutionsInLastDays(Builder $query, int $days)
    {
        return $query->mostSolutions($days);
    }

    public function scopeMostSubmissionsInLastDays(Builder $query, int $days)
    {
        return $query->mostSubmissions($days);
    }

    public function scopeWithCounts(Builder $query)
    {
        return $query->withCount([
            'threadsRelation as threads_count',
            'replyAble as replies_count',
            'replyAble as solutions_count' => function (Builder $query) {
                return $query->join('threads', 'threads.solution_reply_id', '=', 'replies.id')
                    ->where('replyable_type', 'threads');
            },
        ]);
    }

    public function scopeHasActivity(Builder $query)
    {
        return $query->where(function ($query) {
            $query->has('threadsRelation')
                ->orHas('replyAble');
        });
    }

    public function scopeModerators(Builder $query)
    {
        return $query->whereIn('type', [
            self::ADMIN,
            self::MODERATOR,
        ]);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Middleware\VerifyAdmins;
use App\Jobs\BanUser;
use App\Jobs\DeleteUser;
use App\Jobs\UnbanUser;
use App\Models\User;
use App\Policies\UserPolicy;
use App\Queries\SearchUsers;
use Illuminate\Auth\Middleware\Authenticate;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware([Authenticate::class, VerifyAdmins::class]);
    }

    public function index()
    {
        if ($adminSearch = request('admin_search')) {
            $users = SearchUsers::get($adminSearch)->appends(['admin_search' => $adminSearch]);
        } else {
            $users = User::latest()->paginate(20);
        }

        return view('admin.users', compact('users', 'adminSearch'));
    }

    public function ban(User $user)
    {
        $this->authorize(UserPolicy::BAN, $user);

        $this->dispatchNow(new BanUser($user));

        $this->success('admin.users.banned', $user->name());

        return redirect()->route('profile', $user->username());
    }

    public function unban(User $user)
    {
        $this->authorize(UserPolicy::BAN, $user);

        $this->dispatchNow(new UnbanUser($user));

        $this->success('admin.users.unbanned', $user->name());

        return redirect()->route('profile', $user->username());
    }

    public function delete(User $user)
    {
        $this->authorize(UserPolicy::DELETE, $user);

        $this->dispatchNow(new DeleteUser($user));

        $this->success('admin.users.deleted', $user->name());

        return redirect()->route('admin');
    }
}

app/Http/Livewire/NotificationCount.php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use Livewire\Component;

final class NotificationCount extends Component
{
    public $count;

    protected $listeners = [
        'NotificationMarkedAsRead' => 'updateCount',
    ];

    public function render(): View
    {
        $this->count = Auth::user()->unreadNotifications()->count();

        return view('livewire.notification_count', [
            'count' => $this->count,
        ]);
    }

    public function updateCount(int $count): int
    {
        return $count;
    }
}

resources/views/users/_latest_replies.blade.php
<div class="flex flex-col gap-y-6">
    @forelse ($user->latestReplies(5) as $reply)
        <x-users.reply :thread="$reply->replyAble()" :reply="$reply" />
    @empty
        <x-empty-state title="{{ $user->username() }} has not posted any replies yet" icon="heroicon-o-annotation" />
    @endforelse
</div>

resources/views/users/_latest_threads.blade.php
<div class="flex flex-col gap-y-6">
    @forelse ($user->latestThreads() as $thread)
        <x-threads.overview-summary :thread="$thread" />
    @empty
        <x-empty-state title="{{ $user->username() }} has not posted any threads yet" icon="heroicon-o-document-text" />
    @endforelse
</div>

resources/views/users/articles.blade.php
@title('Your Articles')

@extends('layouts.default')

@section('subnav')
    <div class="bg-white border-b">
        <div class="container mx-auto flex justify-between items-center px-4">
            <h1 class="text-xl py-4 text-gray-900 break-all">
                {{ $title }}
            </h1>

            <div class="flex">
                <x-buttons.primary-button href="{{ route('articles.create') }}">
                    Create Article
                </x-buttons.primary-button>
            </div>
        </div>
    </div>
@endsection

@section('content')
    <div class="container mx-auto px-4 py-8">
        @unless(Auth::user()->hasTwitterAccount())
            <x-primary-info-panel icon="heroicon-s-information-circle">
                Set your <a href="{{ route('settings.profile') }}" class="underline">Twitter handle</a> so we can link to your profile when we tweet out your article.
            </x-primary-info-panel>
        @endunless

        <div class="flex flex-col gap-y-4 mb-4">
            @forelse($articles as $article)
                <x-articles.overview-summary :article="$article" :mode="'edit'"/>
            @empty
                <p class="text-gray-600 text-base">
                    You haven't created any articles yet
                </p>
            @endforelse
        </div>

        {{ $articles->links() }}
    </div>
@endsection

resources/views/users/notifications.blade.php
@title('Users')

@extends('layouts.default')

@section('content')
    <div class="container mx-auto px-4 pt-6">
        <div class="border-b border-gray-200 pb-4">
            <div class="sm:flex sm:items-center sm:justify-between sm:items-baseline">
                <div class="sm:flex sm:items-center sm:justify-between sm:items-baseline">
                    <h1 class="flex items-center gap-x-4 text-4xl font-bold text-gray-900">
                        Notifications
                        <livewire:notification-count/>
                    </h1>
                </div>
            </div>
        </div>

        <div class="my-4">
            <livewire:notifications />
        </div>
    </div>
@endsection

resources/views/users/profile.blade.php
@title("{$user->username()} ({$user->name()})")
@canonical(route('profile', $user->username()))

@extends('layouts.default')

@section('content')
    <section class="bg-white">
        <div
            class="bg-gray-900 bg-contain h-60 w-full"
            style="background-image: url('{{ asset('images/profile-background.svg') }}')"
        ></div>

        <div class="container mx-auto">
            <div class="flex justify-center lg:justify-start">
                <x-avatar :user="$user" class="-mt-24 w-48 h-48 rounded-full border-8 border-white" unlinked />
            </div>

            <div class="flex flex-col mt-5 p-4 lg:flex-row lg:gap-x-12">
                <div class="w-full mb-10 lg:w-1/3 lg:mb-0">
                    <div>
                        <div class="flex items-center gap-x-4">
                            <h1 class="text-4xl font-bold">{{ $user->name() }}</h1>

                            @if ($user->isAdmin() || $user->isModerator())
                                <span class="border border-lio-500 text-lio-500 rounded px-3 py-1">
                                    {{ $user->isAdmin() ? 'Admin' : 'Moderator' }}
                                </span>
                            @endif
                        </div>

                        <span class="text-gray-600">
                            Joined {{ $user->createdAt()->format('j M Y') }}
                        </span>
                    </div>

                    <div class="mt-4">
                        <span class="text-gray-900">
                            {{ $user->bio() }}
                        </span>
                    </div>

                    <div class="mt-4 mb-6 flex items-center gap-x-3">
                        @if ($user->githubUsername())
                            <a href="https://github.com/{{ $user->githubUsername() }}">
                                <x-icon-github class="w-6 h-6" />
                            </a>
                        @endif

                        @if ($user->hasTwitterAccount())
                            <a href="https://twitter.com/{{ $user->twitter() }}" class="text-twitter">
                                <x-icon-twitter class="w-6 h-6" />
                            </a>
                        @endif
                    </div>

                    <div class="flex flex-col gap-y-4">
                        @if ($user->isLoggedInUser())
                            <x-buttons.secondary-button href="{{ route('settings.profile') }}" class="w-full">
                                <span class="flex items-center gap-x-2">
                                    <x-heroicon-o-pencil class="w-5 h-5" />
                                    Edit profile
                                </span>
                            </x-buttons.secondary-button>
                        @endif

                        @can(App\Policies\UserPolicy::BAN, $user)
                            @if ($user->isBanned())
                                <x-buttons.secondary-button class="w-full" @click.prevent="activeModal = 'unbanUser'">
                                    <span class="flex items-center gap-x-2">
                                        <x-heroicon-o-check class="w-5 h-5" />
                                        Unban User
                                    </span>
                                </x-buttons.secondary-button>
                            @else
                                <x-buttons.danger-button class="w-full" @click.prevent="activeModal = 'banUser'">
                                    <span class="flex items-center gap-x-2">
                                        <x-icon-hammer class="w-5 h-5" />
                                        Ban User
                                    </span>
                                </x-buttons.danger-button>
                            @endif
                        @endcan

                        @if (Auth::check() && Auth::user()->isAdmin())
                            @can(App\Policies\UserPolicy::DELETE, $user)
                                <x-buttons.danger-button class="w-full" @click.prevent="activeModal = 'deleteUser'">
                                    <span class="flex items-center gap-x-2">
                                        <x-heroicon-o-trash class="w-5 h-5" />
                                        Delete User
                                    </span>
                                </x-buttons.danger-button>
                            @endcan
                        @endif
                    </div>
                </div>

                <div class="w-full lg:w-2/3">
                    <h2 class="text-3xl font-semibold">
                        Statistics
                    </h2>

                    <div class="mt-4 grid grid-cols-1 lg:grid-cols-2">
                        <div class="w-full flex justify-between px-5 py-2.5 bg-gray-100">
                            <span>Threads</span>
                            <span class="text-lio-500">
                                {{ number_format($user->countThreads()) }}
                            </span>
                        </div>

                        <div class="w-full flex justify-between px-5 py-2.5 bg-white lg:bg-gray-100">
                            <span>Replies</span>
                            <span class="text-lio-500">
                                {{ number_format($user->countReplies()) }}
                            </span>
                        </div>

                        <div class="w-full flex justify-between px-5 py-2.5 bg-gray-100 lg:bg-white">
                            <span>Solutions</span>
                            <span class="text-lio-500">
                                {{ number_format($user->countSolutions()) }}
                            </span>
                        </div>

                        <div class="w-full flex justify-between px-5 py-2.5">
                            <span>Articles</span>
                            <span class="text-lio-500">
                                {{ number_format($user->countArticles()) }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            @if ($articles->count() > 0)
                <div class="mt-10 px-4 lg:mt-28">
                    <h2 class="text-3xl font-semibold">
                        Articles
                    </h2>

                    <div class="mt-8 flex flex-col gap-y-8 lg:flex-row lg:gap-x-8 lg:mb-16">
                        @foreach ($articles as $article)
                            <div class="w-full lg:w-1/3">
                                <x-articles.user-summary :article="$article" />
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif
        </div>

        <div class="mt-16 lg:mt-32" x-data="{ tab: 'threads' }">
            <div class="container mx-auto">
                <nav class="flex items-center justify-between lg:justify-start">
                    <button @click="tab = 'threads'" :class="{ 'text-lio-500 border-lio-500 border-b-2': tab === 'threads' }"  class="px-4 whitespace-nowrap py-5 font-medium text-lg text-gray-900 hover:text-lio-500 hover:border-lio-500 focus:outline-none focus:text-lio-500 focus:border-lio-500 lg:w-1/3">
                        Threads posted
                    </button>
                    <button @click="tab = 'replies'" :class="{ 'text-lio-500 border-lio-500 border-b-2': tab === 'replies' }"  class="px-4 whitespace-nowrap py-5 font-medium text-lg text-gray-900 hover:text-lio-500 hover:border-lio-500 focus:outline-none focus:text-lio-500 focus:border-lio-500 lg:w-1/3">
                        Replies posted
                    </button>
                </nav>
            </div>

            <div class="bg-gray-100 py-14 px-4">
                <div class="container mx-auto">
                    <div x-show="tab === 'threads'">
                        @include('users._latest_threads')
                    </div>

                    <div x-show="tab === 'replies'" x-cloak>
                        @include('users._latest_replies')
                    </div>
                </div>
            </div>
        </div>
    </section>

    @can(App\Policies\UserPolicy::BAN, $user)
        @if ($user->isBanned())
            <x-modal
                identifier="unbanUser"
                :action="route('admin.users.unban', $user->username())"
                title="Unban {{ $user->username() }}"
                type="update"
            >
                <p>Unbanning this user will allow them to login again and post content.</p>
            </x-modal>
        @else
            <x-modal
                identifier="banUser"
                :action="route('admin.users.ban', $user->username())"
                title="Ban {{ $user->username() }}"
                type="update"
            >
                <p>Banning this user will prevent them from logging in, posting threads and replying to threads.</p>
            </x-modal>
        @endif
    @endcan

    @can(App\Policies\UserPolicy::DELETE, $user)
        <x-modal
            identifier="deleteUser"
            :action="route('admin.users.delete', $user->username())"
            title="Delete {{ $user->username() }}"
        >
            <p>Deleting this user will remove their account and any related content like threads & replies. This cannot be undone.</p>
        </x-modal>
    @endcan
@endsection