routes/web.php
<?php

use App\Http\Controllers\Admin\ArticlesController as AdminArticlesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Articles\ArticlesController;
use App\Http\Controllers\Articles\AuthoredArticles;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\GithubController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\VerificationController;
use App\Http\Controllers\Forum\TagsController;
use App\Http\Controllers\Forum\ThreadsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReplyAbleController;
use App\Http\Controllers\ReplyController;
use App\Http\Controllers\Settings\ApiTokenController;
use App\Http\Controllers\Settings\PasswordController;
use App\Http\Controllers\Settings\ProfileController as ProfileSettingsController;
use App\Http\Controllers\SocialImageController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Middleware\Authenticate;
use Illuminate\Support\Facades\Route;

Route::feeds();

// Home
Route::get('/', [HomeController::class, 'show'])->name('home');
Route::view('rules', 'rules')->name('rules');
Route::view('terms', 'terms')->name('terms');
Route::view('privacy', 'privacy')->name('privacy');
Route::get('bin/{paste?}', [HomeController::class, 'pastebin']);

Route::get('articles/{article}/social.png', SocialImageController::class)->name('articles.image');

// Authentication
Route::namespace('Auth')->group(function () {
    // Sessions
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.post');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    // Registration
    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register'])->name('register.post');

    // Password reset
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.forgot');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.forgot.post');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.reset.post');

    // Email address verification
    Route::get('email/verify', [VerificationController::class, 'show'])->name('verification.notice');
    Route::get('email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify');
    Route::post('email/resend', [VerificationController::class, 'resend'])->name('verification.resend');

    // Social authentication
    Route::get('login/github', [GithubController::class, 'redirectToProvider'])->name('login.github');
    Route::get('auth/github', [GithubController::class, 'handleProviderCallback']);
});

// Users
Route::redirect('/dashboard', '/user');
Route::get('user/{username?}', [ProfileController::class, 'show'])->name('profile');

// Notifications
Route::view('notifications', 'users.notifications')->name('notifications')->middleware(Authenticate::class);

// Settings
Route::get('settings', [ProfileSettingsController::class, 'edit'])->name('settings.profile');
Route::put('settings', [ProfileSettingsController::class, 'update'])->name('settings.profile.update');
Route::delete('settings', [ProfileSettingsController::class, 'destroy'])->name('settings.profile.delete');
Route::put('settings/password', [PasswordController::class, 'update'])->name('settings.password.update');
Route::post('settings/api-tokens', [ApiTokenController::class, 'store'])->name('settings.api-tokens.store');
Route::delete('settings/api-tokens', [ApiTokenController::class, 'destroy'])->name('settings.api-tokens.delete');

// Forum
Route::prefix('forum')->group(function () {
    Route::get('/', [ThreadsController::class, 'overview'])->name('forum');
    Route::get('create-thread', [ThreadsController::class, 'create'])->name('threads.create');
    Route::post('create-thread', [ThreadsController::class, 'store'])->name('threads.store');

    Route::get('{thread}', [ThreadsController::class, 'show'])->name('thread');
    Route::get('{thread}/edit', [ThreadsController::class, 'edit'])->name('threads.edit');
    Route::put('{thread}', [ThreadsController::class, 'update'])->name('threads.update');
    Route::delete('{thread}', [ThreadsController::class, 'delete'])->name('threads.delete');
    Route::post('{thread}/lock', [ThreadsController::class, 'lock'])->name('threads.lock');
    Route::put('{thread}/mark-solution/{reply}', [ThreadsController::class, 'markSolution'])->name('threads.solution.mark');
    Route::put('{thread}/unmark-solution', [ThreadsController::class, 'unmarkSolution'])->name('threads.solution.unmark');
    Route::post('{thread}/subscribe', [ThreadsController::class, 'subscribe'])->name('threads.subscribe');
    Route::post('{thread}/unsubscribe', [ThreadsController::class, 'unsubscribe'])->name('threads.unsubscribe');

    Route::get('tags/{tag}', [TagsController::class, 'show'])->name('forum.tag');
});

// Replies
Route::post('replies', [ReplyController::class, 'store'])->name('replies.store');
Route::get('replies/{reply}/edit', [ReplyController::class, 'edit'])->name('replies.edit');
Route::put('replies/{reply}', [ReplyController::class, 'update'])->name('replies.update');
Route::delete('replies/{reply}', [ReplyController::class, 'delete'])->name('replies.delete');
Route::get('replyable/{id}/{type}', [ReplyAbleController::class, 'redirect'])->name('replyable');

// Subscriptions
Route::get('subscriptions/{subscription}/unsubscribe', [SubscriptionController::class, 'unsubscribe'])
    ->name('subscriptions.unsubscribe');

// Articles
Route::prefix('articles')->group(function () {
    Route::get('authored', AuthoredArticles::class)->name('user.articles');
    Route::get('/', [ArticlesController::class, 'index'])->name('articles');
    Route::get('create', [ArticlesController::class, 'create'])->name('articles.create');
    Route::post('/', [ArticlesController::class, 'store'])->name('articles.store');
    Route::get('{article}', [ArticlesController::class, 'show'])->name('articles.show');
    Route::get('{article}/edit', [ArticlesController::class, 'edit'])->name('articles.edit');
    Route::put('{article}', [ArticlesController::class, 'update'])->name('articles.update');
    Route::delete('{article}', [ArticlesController::class, 'delete'])->name('articles.delete');
});

// Admin
Route::prefix('admin')->name('admin')->group(function () {
    Route::get('/', [AdminArticlesController::class, 'index']);

    // Users
    Route::get('users', [UsersController::class, 'index'])->name('.users');
    Route::put('users/{username}/ban', [UsersController::class, 'ban'])->name('.users.ban');
    Route::put('users/{username}/unban', [UsersController::class, 'unban'])->name('.users.unban');
    Route::delete('users/{username}', [UsersController::class, 'delete'])->name('.users.delete');

    // Articles
    Route::put('articles/{article}/approve', [AdminArticlesController::class, 'approve'])->name('.articles.approve');
    Route::put('articles/{article}/disapprove', [AdminArticlesController::class, 'disapprove'])->name('.articles.disapprove');
    Route::put('articles/{article}/decline', [AdminArticlesController::class, 'decline'])->name('.articles.decline');
    Route::put('articles/{article}/pinned', [AdminArticlesController::class, 'togglePinnedStatus'])->name('.articles.pinned');
});

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Middleware\VerifyAdmins;
use App\Jobs\ApproveArticle;
use App\Jobs\DeclineArticle;
use App\Jobs\DisapproveArticle;
use App\Models\Article;
use App\Policies\ArticlePolicy;
use App\Queries\SearchArticles;
use Illuminate\Auth\Middleware\Authenticate;

class ArticlesController extends Controller
{
    public function __construct()
    {
        $this->middleware([Authenticate::class, VerifyAdmins::class]);
    }

    public function index()
    {
        if ($adminSearch = request('admin_search')) {
            $articles = SearchArticles::get($adminSearch)->appends(['admin_search' => $adminSearch]);
        } else {
            $articles = Article::awaitingApproval()
                ->orderByDesc('submitted_at')
                ->paginate();
        }

        return view('admin.articles', compact('articles', 'adminSearch'));
    }

    public function approve(Article $article)
    {
        $this->authorize(ArticlePolicy::APPROVE, $article);

        $this->dispatchNow(new ApproveArticle($article));

        $this->success('admin.articles.approved', $article->title());

        return redirect()->route('articles.show', $article->slug());
    }

    public function disapprove(Article $article)
    {
        $this->authorize(ArticlePolicy::DISAPPROVE, $article);

        $this->dispatchNow(new DisapproveArticle($article));

        $this->success('admin.articles.disapproved', $article->title());

        return redirect()->route('articles.show', $article->slug());
    }

    public function decline(Article $article)
    {
        $this->authorize(ArticlePolicy::DECLINE, $article);

        $this->dispatchNow(new DeclineArticle($article));

        return redirect()->route('articles.show', $article->slug());
    }

    public function togglePinnedStatus(Article $article)
    {
        $this->authorize(ArticlePolicy::PINNED, $article);

        $article->is_pinned = ! $article->isPinned();
        $article->save();

        $this->success($article->isPinned() ? 'admin.articles.pinned' : 'admin.articles.unpinned');

        return redirect()->route('articles.show', $article->slug());
    }
}

app/Http/Controllers/Articles/ArticlesController.php
<?php

namespace App\Http\Controllers\Articles;

use App\Concerns\UsesFilters;
use App\Http\Controllers\Controller;
use App\Http\Middleware\Authenticate;
use App\Http\Requests\ArticleRequest;
use App\Http\Resources\ArticleResource;
use App\Jobs\CreateArticle;
use App\Jobs\DeleteArticle;
use App\Jobs\UpdateArticle;
use App\Models\Article;
use App\Models\Tag;
use App\Models\User;
use App\Policies\ArticlePolicy;
use Illuminate\Auth\Middleware\EnsureEmailIsVerified;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Symfony\Component\HttpFoundation\Response;

class ArticlesController extends Controller
{
    use UsesFilters;

    public function __construct()
    {
        $this->middleware([Authenticate::class, EnsureEmailIsVerified::class], ['except' => ['index', 'show']]);
    }

    public function index(Request $request)
    {
        $filter = $this->getFilter(['recent', 'popular', 'trending']);

        $pinnedArticles = Article::published()
            ->pinned()
            ->latest('submitted_at')
            ->take(4)
            ->get();

        $articles = Article::published()
            ->notPinned()
            ->{$filter}();

        $tags = Tag::whereHas('articles', function ($query) {
            $query->published();
        })->orderBy('name')->get();

        if ($activeTag = Tag::where('slug', $request->tag)->first()) {
            $articles->forTag($activeTag->slug());
        }

        $moderators = Cache::remember('moderators', now()->addMinutes(30), function () {
            return User::moderators()->get();
        });

        $canonical = canonical('articles', ['filter' => $filter, 'tag' => $activeTag?->slug()]);
        $topAuthors = Cache::remember('topAuthors', now()->addMinutes(30), function () {
            return User::mostSubmissionsInLastDays(365)->take(5)->get();
        });

        return view('articles.overview', [
            'pinnedArticles' => $pinnedArticles,
            'articles' => $articles->paginate(10),
            'tags' => $tags,
            'activeTag' => $activeTag,
            'filter' => $filter,
            'moderators' => $moderators,
            'canonical' => $canonical,
            'topAuthors' => $topAuthors,
        ]);
    }

    public function show(Article $article)
    {
        $user = Auth::user();

        abort_unless(
            $article->isPublished() || ($user && ($article->isAuthoredBy($user) || $user->isAdmin() || $user->isModerator())),
            404,
        );

        $trendingArticles = Article::published()
            ->trending()
            ->whereKeyNot($article->id)
            ->limit(3)
            ->get();

        return view('articles.show', [
            'article' => $article,
            'trendingArticles' => $trendingArticles,
        ]);
    }

    public function create()
    {
        return view('articles.create', [
            'tags' => Tag::all(),
            'selectedTags' => old('tags', []),
        ]);
    }

    public function store(ArticleRequest $request)
    {
        $article = $this->dispatchSync(CreateArticle::fromRequest($request));

        $this->success($request->shouldBeSubmitted() ? 'articles.submitted' : 'articles.created');

        return $request->wantsJson()
            ? ArticleResource::make($article)
            : redirect()->route('articles.show', $article->slug());
    }

    public function edit(Article $article)
    {
        $this->authorize(ArticlePolicy::UPDATE, $article);

        return view('articles.edit', [
            'article' => $article,
            'tags' => Tag::all(),
            'selectedTags' => old('tags', $article->tags()->pluck('id')->toArray()),
        ]);
    }

    public function update(ArticleRequest $request, Article $article)
    {
        $this->authorize(ArticlePolicy::UPDATE, $article);

        $wasNotPreviouslySubmitted = $article->isNotSubmitted();

        $article = $this->dispatchSync(UpdateArticle::fromRequest($article, $request));

        if ($wasNotPreviouslySubmitted && $request->shouldBeSubmitted()) {
            $this->success('articles.submitted');
        } else {
            $this->success('articles.updated');
        }

        return $request->wantsJson()
            ? ArticleResource::make($article)
            : redirect()->route('articles.show', $article->slug());
    }

    public function delete(Request $request, Article $article)
    {
        $this->authorize(ArticlePolicy::DELETE, $article);

        $this->dispatchSync(new DeleteArticle($article));

        $this->success('articles.deleted');

        return $request->wantsJson()
            ? response()->json([], Response::HTTP_NO_CONTENT)
            : redirect()->route('articles');
    }
}

app/Http/Controllers/Articles/AuthoredArticles.php
<?php

namespace App\Http\Controllers\Articles;

use App\Http\Controllers\Controller;
use App\Http\Middleware\Authenticate;
use Illuminate\Auth\Middleware\EnsureEmailIsVerified;
use Illuminate\Http\Request;

class AuthoredArticles extends Controller
{
    public function __construct()
    {
        $this->middleware([Authenticate::class, EnsureEmailIsVerified::class]);
    }

    public function __invoke(Request $request)
    {
        return view('users.articles', [
            'articles' => $request->user()
                ->articles()
                ->orderByDesc('submitted_at')
                ->orderByDesc('created_at')
                ->paginate(10),
        ]);
    }
}

app/Http/Livewire/LikeArticle.php
<?php

namespace App\Http\Livewire;

use App\Jobs\LikeArticle as LikeArticleJob;
use App\Jobs\UnlikeArticle as UnlikeArticleJob;
use App\Models\Article;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

final class LikeArticle extends Component
{
    use DispatchesJobs;

    public $article;

    public $isSidebar = true;

    protected $listeners = ['likeToggled'];

    public function mount(Article $article): void
    {
        $this->article = $article;
    }

    public function toggleLike(): void
    {
        if (Auth::guest()) {
            return;
        }

        if ($this->article->isLikedBy(Auth::user())) {
            $this->dispatchNow(new UnlikeArticleJob($this->article, Auth::user()));
        } else {
            $this->dispatchNow(new LikeArticleJob($this->article, Auth::user()));
        }

        $this->emit('likeToggled');
    }

    public function likeToggled()
    {
        return $this->article;
    }
}

resources/views/articles/create.blade.php
@title('Write your article')

@extends('layouts.default')

@section('subnav')
    <div class="bg-white border-b">
        <div class="container mx-auto flex justify-between items-center px-4">
            <h1 class="text-xl py-4 text-gray-900">
                <a href="{{ route('user.articles') }}">Your Articles</a>
                > <span class="break-all">{{ $title }}</span>
            </h1>
        </div>
    </div>
@endsection

@section('content')
    <main class="max-w-4xl mx-auto pt-10 pb-12 px-4 lg:pb-16">        
        <div class="lg:grid lg:gap-x-5">
            <div class="sm:px-6 lg:px-0 lg:col-span-9">
                <x-articles.form :route="['articles.store']" :tags="$tags" :selectedTags="$selectedTags" />
            </div>
        </div>
    </main>
@endsection

resources/views/articles/edit.blade.php
@title('Edit your article')

@extends('layouts.default')

@section('subnav')
    <div class="bg-white border-b">
        <div class="container mx-auto flex justify-between items-center px-4">
            <h1 class="text-xl py-4 text-gray-900">
                <a href="{{ route('user.articles') }}">Your Articles</a>
                > <span class="break-all">{{ $title }}</span>
            </h1>
        </div>
    </div>
@endsection

@section('content')
    <main class="max-w-4xl mx-auto pt-10 pb-12 px-4 lg:pb-16">        
        <div class="lg:grid lg:gap-x-5">
            <div class="sm:px-6 lg:px-0 lg:col-span-9">
                <x-articles.form 
                    :route="['articles.update', $article->slug()]" 
                    method="PUT"
                    :article="$article"
                    :tags="$tags"
                    :selectedTags="$selectedTags"
                />

                <x-forms.info>
                    After submission for approval, articles are reviewed before being published. No notification of declined articles will be provided. Instead, we encourage to also cross-post articles on your own channel as well.
                </x-forms.info>
            </div>
        </div>
    </main>
@endsection

resources/views/articles/show.blade.php
@title($article->title())
@canonical($article->canonicalUrl())
@shareImage(route('articles.image', $article->slug()))

@extends('layouts.default')

@section('content')
    <article class="bg-white">
        @if ($article->isDeclined() && (Auth::user()->isAdmin() || Auth::user()->isModerator()))
            <div class="w-full text-white bg-lio-500 p-4">
                <div class="text-center container mx-auto px-4">
                    {{ __('admin.articles.declined') }}
                </div>
            </div>
        @endif

        <div class="w-full bg-center bg-cover bg-gray-900" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url({{ $article->heroImage(2000, 384) }});">
            <div class="container mx-auto">
                <div class="px-4 lg:px-0 lg:mx-48">
                    <div class="flex items-center justify-between pt-6 mb-28">
                        <a href="{{ route('articles') }}" class="hidden items-center text-base text-white hover:underline lg:flex">
                            <x-heroicon-s-arrow-left class="w-4 h-4 fill-current" />
                            <span class="text-white ml-1 hover:text-gray-100">Back to articles</span>
                        </a>

                        <div class="hidden lg:flex">
                            @if ($article->isNotPublished())
                                <x-light-tag>
                                    @if ($article->isAwaitingApproval())
                                        Awaiting Approval
                                    @else
                                        Draft
                                    @endif
                                </x-light-tag>
                            @endif
                        </div>
                    </div>

                    @if (count($tags = $article->tags()))
                        <div class="flex flex-wrap gap-2 lg:gap-x-4 mb-4">
                            @foreach ($tags as $tag)
                                <x-light-tag>
                                    {{ $tag->name() }}
                                </x-light-tag>
                            @endforeach
                        </div>
                    @endif

                    <h1 class="text-white text-5xl font-bold mb-4 break-words">
                        {{ $article->title() }}
                    </h1>

                    <div class="flex flex-col gap-y-2 text-white pb-4 lg:pb-12 lg:flex-row lg:items-center">
                        <div class="flex items-center">
                            <x-avatar :user="$article->author()" class="w-6 h-6 rounded-full mr-3" />

                            <a href="{{ route('profile', $article->author()->username()) }}" class="hover:underline">
                                <span class="mr-5">{{ $article->author()->name() }}</span>
                            </a>
                        </div>

                        <div class="flex items-center">
                            <span class="font-mono text-sm mr-6 lg:mt-0">
                                {{ $article->createdAt()->format('j M, Y') }}
                            </span>

                            <span class="text-sm">
                                {{ $article->readTime() }} min read
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container mx-auto">
            <div class="flex px-4 lg:px-0 lg:mx-48">
                <div class="hidden lg:block lg:w-1/5">
                    <div class="py-12 mt-48 sticky top-0">
                        <x-articles.engage :article="$article" />
                    </div>
                </div>

                <div class="w-full pt-4 lg:w-4/5 lg:pt-10">
                    @if (! $article->isDeclined() || $article->isAuthoredBy(Auth::user()))
                        <x-articles.actions :article="$article" />
                    @endif

                    <div
                        x-data="{}"
                        x-init="$nextTick(function () { highlightCode($el); })"
                        class="prose prose-lg text-gray-800 prose-lio"
                    >
                        <x-buk-markdown>{!! $article->body() !!}</x-buk-markdown>
                    </div>

                    @if ($article->isUpdated())
                        <div class="text-sm text-gray-900 py-6">
                            Last updated {{ $article->updated_at->diffForHumans() }}.
                        </div>
                    @endif

                    <div class="flex items-center gap-x-6 pt-6 pb-10">
                        <livewire:like-article :article="$article" :isSidebar="false" />

                        <div class="flex flex-col text-gray-900 text-xl font-semibold">
                            Like this article?
                            <span class="text-lg font-medium">
                                Let the author know and give them a clap!
                            </span>
                        </div>
                    </div>

                    <div class="border-t-2 border-gray-200 py-8 lg:pt-14 lg:pb-16">
                        <div class="flex flex-col items-center justify-center gap-y-4 lg:flex-row lg:justify-between">
                            <div class="flex items-start gap-x-4">
                                <div class="shrink-0">
                                    <x-avatar :user="$article->author()" class="hidden w-16 h-16 lg:block" />
                                </div>

                                <div class="flex flex-col items-center text-gray-900 text-xl font-semibold lg:items-start">
                                    <a href="{{ route('profile', $article->author()->username()) }}" class="hover:underline">
                                        {{ $article->author()->username() }} ({{ $article->author()->name() }})
                                    </a>

                                    <span class="text-lg text-gray-700 font-medium">
                                        {{ $article->author()->bio() }}
                                    </span>
                                </div>
                            </div>

                            <div class="flex items-center gap-x-6">
                                @if ($article->author()->githubUsername())
                                    <a href="https://github.com/{{ $article->author()->githubUsername() }}">
                                        <x-icon-github class="w-6 h-6" />
                                    </a>
                                @endif

                                @if ($article->author()->hasTwitterAccount())
                                    <a href="https://twitter.com/{{ $article->author()->twitter() }}" class="text-twitter">
                                        <x-icon-twitter class="w-6 h-6" />
                                    </a>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>

    <section>
        <div class="container mx-auto py-6 px-4 lg:py-24">
            <h2 class="text-4xl text-gray-900 font-bold">
                Other articles you might like
            </h2>

            <div class="flex flex-col gap-y-4 gap-x-6 mt-6 lg:flex-row lg:mt-12">
                @foreach ($trendingArticles as $trendingArticle)
                    <x-articles.summary
                        :article="$trendingArticle"
                        is-featured
                    />
                @endforeach
            </div>
        </div>
    </section>

    @can(App\Policies\ArticlePolicy::APPROVE, $article)
        @if ($article->isAwaitingApproval())
            <x-modal
                identifier="approveArticle"
                :action="route('admin.articles.approve', $article->slug())"
                title="Approve article"
                type="update"
            >
                <p>Are you sure you want to approve this article?</p>
            </x-modal>
        @endif
    @endcan

    @can(App\Policies\ArticlePolicy::DISAPPROVE, $article)
        @if ($article->isPublished())
            <x-modal
                identifier="unpublishArticle"
                :action="route('admin.articles.disapprove', $article->slug())"
                title="Unpublish article"
                type="update"
            >
                <p>Are you sure you want to unpublish this article? Doing so will mean it is no longer live on the site.</p>
            </x-modal>
        @endif
    @endcan

    @can(App\Policies\ArticlePolicy::DECLINE, $article)
        @if ($article->isNotDeclined())
            <x-modal
                identifier="declineArticle"
                :action="route('admin.articles.decline', $article->slug())"
                title="Decline article"
                type="update"
            >
                <p>Are you sure you want to decline this article? Doing so will permanently remove it from the review queue.</p>
            </x-modal>
        @endif
    @endcan

    @can(App\Policies\ArticlePolicy::DELETE, $article)
        <x-modal
            identifier="deleteArticle"
            :action="route('articles.delete', $article->slug())"
            title="Delete article"
        >
            <p>Are you sure you want to delete this article? Doing so will mean it is permanently removed from the site.</p>
        </x-modal>
    @endcan

    @can(App\Policies\ArticlePolicy::PINNED, $article)
        <x-modal
            identifier="togglePinnedStatus"
            :action="route('admin.articles.pinned', $article->slug())"
            :title="$article->isPinned() ? 'Unpin article' : 'Pin article'"
            type="update"
        >
            @if ($article->isPinned())
                <p>Are you sure you want to unpin this article?</p>
            @else
                <p>Are you sure you want to pin this article?</p>
            @endif
        </x-modal>
    @endcan
@endsection